CREATE TABLE IF NOT EXISTS programmes (
    id                  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code                VARCHAR(30) NOT NULL,
    title               VARCHAR(150) NOT NULL,
    slug                VARCHAR(150) NOT NULL,
    category_id         BIGINT UNSIGNED NULL,
    description         TEXT NULL,
    objectives          TEXT NULL,
    requirements        TEXT NULL,
    duration_weeks      SMALLINT UNSIGNED NULL,
    delivery_mode       ENUM('physical','online','hybrid') NOT NULL DEFAULT 'physical',
    fee_amount          BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'minor units (kobo)',
    currency            CHAR(3) NOT NULL DEFAULT 'NGN',
    capacity            SMALLINT UNSIGNED NULL,
    grants_certificate  TINYINT(1) NOT NULL DEFAULT 1,
    status              ENUM('draft','pending_approval','approved','published','archived') NOT NULL DEFAULT 'draft',
    published_at        TIMESTAMP NULL DEFAULT NULL,
    created_by          BIGINT UNSIGNED NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_programmes_code (code),
    UNIQUE KEY uq_programmes_slug (slug),
    CONSTRAINT fk_programmes_category FOREIGN KEY (category_id) REFERENCES programme_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_programmes_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
