CREATE TABLE IF NOT EXISTS applications (
    id                   BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reference            VARCHAR(30) NOT NULL,
    user_id              BIGINT UNSIGNED NOT NULL,
    programme_id         BIGINT UNSIGNED NOT NULL,
    preferred_centre_id  BIGINT UNSIGNED NULL COMMENT 'NULL = online delivery',
    cohort_id            BIGINT UNSIGNED NULL COMMENT 'assigned at approval, not at submission',
    status               ENUM('draft','submitted','under_review','approved','rejected','withdrawn') NOT NULL DEFAULT 'draft',
    motivation           TEXT NULL,
    submitted_at         TIMESTAMP NULL DEFAULT NULL,
    reviewed_by          BIGINT UNSIGNED NULL,
    reviewed_at          TIMESTAMP NULL DEFAULT NULL,
    decision_note        TEXT NULL,
    created_by           BIGINT UNSIGNED NULL COMMENT 'differs from user_id when staff apply on someone behalf',
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_applications_reference (reference),
    KEY ix_applications_user (user_id, status),
    KEY ix_applications_centre (preferred_centre_id, status),
    KEY ix_applications_programme (programme_id, status),
    CONSTRAINT fk_applications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_programme FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_centre FOREIGN KEY (preferred_centre_id) REFERENCES centres(id) ON DELETE SET NULL,
    CONSTRAINT fk_applications_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id) ON DELETE SET NULL,
    CONSTRAINT fk_applications_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_applications_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
